using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Amazon.Route53;
using Amazon.Route53.Model;

using log4net;

using Route53DDNS.type;

namespace Route53DDNS.client
{
    // Shall be recreated on each timed run
    class Route53Client
    {
        private static readonly ILog logger = LogManager.GetLogger(typeof(Route53Client).FullName);
        private AmazonRoute53Client client;

        public Route53Client(string awsAccessKey, string awsSecretKey)
        {
            logger.Info("Creating Route53 client");
            client = new AmazonRoute53Client(awsAccessKey, awsSecretKey);
        }

        public ListResourceRecordSetsResponse listRecordSets(string hostedZoneId, string startRecordIdentifier)
        {
            logger.Info("Calling ListResourceRecordSets");
            // there is a bug in AWS autogenerated request client see, if you add anything else except HZ it will fail as of 1.4.6
            // https://forums.aws.amazon.com/thread.jspa?threadID=87054
            ListResourceRecordSetsRequest request = new ListResourceRecordSetsRequest();
            request.HostedZoneId = hostedZoneId;
            // this line will cause it to throw a weird error
            // request.MaxItems = "100";
            request.StartRecordIdentifier = startRecordIdentifier;
            return client.ListResourceRecordSets(request); ;
        }
    }
}
